[build]
builder = "nixpacks"
watchPatterns = ["server/**"]
nixpacksConfigPath = "server/nixpacks.toml"

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
